name: pluto
description: private underground events

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.2
  file_picker: ^10.3.2
  url_launcher: ^6.1.7
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.4
  flutter_native_splash: ^2.3.1
  intl: any
  go_router: ^16.1.0
  flutter_widget_from_html: ^0.16.1
  mobile_scanner: ^6.0.11
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf

  assets:
    - assets/home/constant/email.png
    - assets/home/constant/facebook.png
    - assets/home/constant/instagram.png
    - assets/home/constant/link.png
    - assets/home/constant/tiktok.png
    - assets/experience/pluto-logo-small.webp
    - assets/events/Mana-Fest-2026-Flyer-half.webp
    - assets/events/manafest-2026-lineup-v1.webp
