import { randomUUID } from 'node:crypto';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { getStorage } from 'firebase-admin/storage';
import { consents, consentVersion, documentHash, electronicDisclosure, hash, sourcePdf, sourcePdfHash, version, waiverText } from './document';
import { createSignedPdf, type SigningRecord } from './pdf';
import { normalizeSearch, WaiverError, type Submission } from './validation';
import { storageBucket } from '../deployment-config';

const collection = 'manafestWaivers';
export class WaiverService {
  private db = getFirestore();
  private bucket = getStorage().bucket(storageBucket('waiver'));

  async rateLimit(identity: string, lane: string, limit: number) {
    const hour = Math.floor(Date.now() / 3600000);
    const ref = this.db.collection('waiverRateLimits').doc(hash(`${hour}:${lane}:${identity}`));
    await this.db.runTransaction(async tx => {
      const state = await tx.get(ref);
      const count = state.data()?.count || 0;
      if (count >= limit) throw new WaiverError(429, 'Too many requests. Please try again in an hour, or sign on paper at check-in.');
      tx.set(ref, { count: count + 1, expiresAt: Timestamp.fromMillis((hour + 2) * 3600000) });
    });
  }

  async requireStaff(token: string) {
    let uid: string;
    try { uid = (await getAuth().verifyIdToken(token, true)).uid; }
    catch { throw new WaiverError(401, 'Sign in with your existing staff account to continue.'); }
    if (!(await this.db.collection('adminUsers').doc(uid).get()).exists) throw new WaiverError(403, 'This account is not authorized to access attendee waivers.');
    return uid;
  }

  private async preserveObject(path: string, data: Buffer) {
    const file = this.bucket.file(path);
    try {
      await file.save(data, { resumable: false, contentType: 'application/pdf', preconditionOpts: { ifGenerationMatch: 0 }, metadata: { cacheControl: 'private, no-store' } });
    } catch (error: any) {
      // A concurrent request or an earlier uncertain upload may have succeeded.
      if (Number(error.code) !== 412) throw error;
    }
    const [saved] = await file.download();
    return saved;
  }

  async submit(key: string, input: Submission) {
    const ref = this.db.collection(collection).doc(hash(key));
    const payloadHash = hash(JSON.stringify(input));
    const existing = await ref.get();
    if (!existing.exists) {
      if (input.version !== version || input.documentHash !== documentHash || input.consentVersion !== consentVersion) throw new WaiverError(409, 'The waiver has changed. Reload and review the current waiver before signing.');
      // Preserve the source independently of future deployments before reserving a record.
      const saved = await this.preserveObject(`private/waiverVersions/${sourcePdfHash}.pdf`, sourcePdf);
      if (hash(saved) !== sourcePdfHash) throw new Error('Source integrity failure');
    }
    const record = await this.db.runTransaction(async tx => {
      const snapshot = await tx.get(ref);
      if (snapshot.exists) {
        const data = snapshot.data()!;
        if (data.payloadHash !== payloadHash) throw new WaiverError(409, 'This signing attempt already has different details. Retry with the original details.');
        return data;
      }
      // Both the timestamp and confirmation are generated by the server, never the client.
      const now = Timestamp.now();
      const confirmationId = `MF26-${randomUUID().toUpperCase()}`;
      const data = {
        ...input, signature: JSON.stringify(input.signature), payloadHash, confirmationId, signedAt: now, signedAtUtc: now.toDate().toISOString(),
        status: 'pending', waiverText, sourcePdfHash, consentText: consents, electronicDisclosure,
        sourcePath: `private/waiverVersions/${sourcePdfHash}.pdf`,
        pdfPath: `private/waivers/${confirmationId}.pdf`,
        nameSearch: normalizeSearch(input.fullName), emailSearch: normalizeSearch(input.email), confirmationSearch: normalizeSearch(confirmationId),
      };
      tx.create(ref, data); return data;
    });
    if (record.status === 'completed') return this.confirmation(record);
    const [original] = await this.bucket.file(record.sourcePath).download();
    if (hash(original) !== record.sourcePdfHash) throw new Error('Source integrity failure');
    const pdf = await createSignedPdf({ ...record, signature: JSON.parse(record.signature) } as SigningRecord, original);
    const saved = await this.preserveObject(record.pdfPath, pdf);
    const pdfHash = hash(saved);
    // Completion is only committed after the private PDF has been read back successfully.
    await this.db.runTransaction(async tx => {
      const latest = (await tx.get(ref)).data()!;
      if (latest.status !== 'completed') tx.update(ref, { status: 'completed', pdfHash, completedAt: Timestamp.now() });
    });
    return this.confirmation({ ...record, status: 'completed' });
  }

  private confirmation(record: any) {
    return { status: 'completed', confirmationId: record.confirmationId, signedAtUtc: record.signedAtUtc };
  }

  async download(key: string) {
    return this.downloadRecord((await this.db.collection(collection).doc(hash(key)).get()).data());
  }
  private async downloadRecord(record: any) {
    if (!record || record.status !== 'completed') throw new WaiverError(404, 'A completed waiver is not available. Retry your submission if saving was interrupted.');
    const [pdf] = await this.bucket.file(record.pdfPath).download();
    if (hash(pdf) !== record.pdfHash) throw new Error('Signed PDF integrity failure');
    return { pdf, confirmationId: record.confirmationId };
  }
  async staffDownload(confirmationId: string, uid: string) {
    const docs = await this.db.collection(collection).where('confirmationId', '==', confirmationId).limit(1).get();
    const result = await this.downloadRecord(docs.docs[0]?.data());
    await this.db.collection('waiverAccessLog').add({ staffUid: uid, action: 'download', confirmationId, at: Timestamp.now() });
    return result;
  }
  async search(query: string, uid: string) {
    const q = normalizeSearch(query);
    const results = await Promise.all(['nameSearch', 'emailSearch', 'confirmationSearch'].map(field =>
      this.db.collection(collection).orderBy(field).startAt(q).endAt(`${q}\uf8ff`).limit(26).get(),
    ));
    const records = new Map<string, any>();
    for (const result of results) for (const doc of result.docs) {
      const d = doc.data();
      if (d.status === 'completed') records.set(d.confirmationId, { confirmationId: d.confirmationId, fullName: d.fullName, email: d.email, signedAtUtc: d.signedAtUtc, status: 'completed' });
    }
    await this.db.collection('waiverAccessLog').add({ staffUid: uid, action: 'search', at: Timestamp.now() });
    return { results: [...records.values()].slice(0, 25), truncated: records.size > 25 || results.some(r => r.size === 26) };
  }
}
