platform :ios, '15.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug, 'Profile' => :release, 'Release' => :release,
  'Debug-staging' => :debug, 'Profile-staging' => :release, 'Release-staging' => :release,
  'Debug-production' => :debug, 'Profile-production' => :release, 'Release-production' => :release,
}

def flutter_root
  config = File.expand_path(File.join('Flutter', 'Generated.xcconfig'), __dir__)
  raise "Run flutter pub get before pod install" unless File.exist?(config)
  File.foreach(config) do |line|
    match = line.match(/FLUTTER_ROOT\=(.*)/)
    return match[1].strip if match
  end
  raise "FLUTTER_ROOT is missing from Generated.xcconfig"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
