const assert = require('node:assert/strict');
const { randomUUID, randomBytes } = require('node:crypto');
const { resolve } = require('node:path');
const { createRequire } = require('node:module');
const { chromium } = require('playwright');
const { revealText, walletTop } = require('./flutter-wallet-scroll.cjs');
const { default: AxeBuilder } = require('@axe-core/playwright');
const fillFlutterInput = require('../ci/flutter-input.cjs');
const backend = createRequire(resolve(__dirname, '../../functions/package.json'));
process.env.GCLOUD_PROJECT = 'demo-pluto-ticketing';
process.env.FIRESTORE_EMULATOR_HOST = '127.0.0.1:8185';
process.env.FIREBASE_AUTH_EMULATOR_HOST = '127.0.0.1:9095';
process.env.FIREBASE_STORAGE_EMULATOR_HOST = '127.0.0.1:9295';
process.env.TICKETING_STORAGE_BUCKET = 'demo-pluto-ticketing.appspot.com';
backend('firebase-admin/app').initializeApp({ projectId: 'demo-pluto-ticketing' });
const db = backend('firebase-admin/firestore').getFirestore();
const base = 'http://127.0.0.1:4173';
const key = () => randomBytes(32).toString('hex');
let activePage;
let stage = 'editor';
async function api(page, path, data = {}) {
  return page.evaluate(async ({ path, data }) => {
    const { getAuth } = await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js');
    const token = await getAuth().currentUser?.getIdToken();
    const response = await fetch(`/tickets/api/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(data) });
    const result = await response.json(); if (!response.ok) throw new Error(result.error); return result;
  }, { path, data });
}
async function staff(page, route = '/tickets/admin') {
  await page.goto(`${base}${route}`);
  await page.getByRole('button', { name: 'Local preview staff sign-in' }).click();
  await page.locator('#staff-controls:not([hidden])').waitFor();
}
async function semantics(page) {
  await page.locator('flt-semantics-placeholder').evaluate(e => e.click(), { timeout: 15000 }).catch(() => {});
}
async function settled(page) {
  await page.evaluate(async () => {
    await document.fonts.ready;
    await Promise.all(document.getAnimations().filter(a => a.effect?.getComputedTiming().endTime !== Infinity).map(a => a.finished.catch(() => {})));
  });
}
async function surface(page, name) {
  await settled(page);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${name} fits the viewport`);
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  assert.deepEqual(result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), [], `${name} accessibility`);
  await page.screenshot({ path: `tmp/ticketing-${name}.png`, fullPage: true });
}
(async () => {
  const browser = await chromium.launch();
  try {
    stage = 'app sign-in';
    const signInContext = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 900 } });
    const signIn = await signInContext.newPage(); activePage = signIn;
    signIn.on('pageerror', error => console.error('App startup error:', error.message));
    const concurrentContext = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 390, height: 844 } });
    const concurrentSignIn = await concurrentContext.newPage();
    const signInPages = [signIn, concurrentSignIn];
    for (const app of signInPages) {
      await app.goto(`${base}/app/sign-on`); await semantics(app);
      await app.getByRole('textbox', { name: /Email/ }).fill('staff@ticketing-preview.invalid');
      await app.getByRole('button', { name: 'Continue', exact: true }).click();
      await app.getByLabel(/Enter your password/).fill('Local-ticketing-preview-2026!');
    }
    await Promise.all(signInPages.map(app => app.getByRole('button', { name: 'Sign In', exact: true }).click()));
    for (const app of signInPages) {
      await app.waitForURL(`${base}/app/`);
      await app.getByRole('button', { name: 'Browse Rewards', exact: true }).waitFor();
      assert.equal(await app.getByText('Could not initialize your Pluto Points.', { exact: true }).count(), 0);
    }
    await concurrentContext.close(); await signInContext.close();
    const googleContext = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 900 } });
    const google = await googleContext.newPage(); activePage = google;
    await google.goto(`${base}/app/sign-on`); await semantics(google);
    const popupReady = google.waitForEvent('popup', { timeout: 15000 }).catch(() => null);
    await google.getByRole('button', { name: 'Continue with Google', exact: true }).click();
    const popup = await popupReady; assert.ok(popup, 'Google sign-in should open the emulator popup'); await popup.waitForLoadState('domcontentloaded');
    assert.equal(new URL(popup.url()).origin, 'http://127.0.0.1:9095', 'Google preview sign-in stays in the Auth emulator');
    await popup.close(); await googleContext.close();
    if (process.argv.includes('--sign-in-only')) { console.log('App sign-in checks passed: seeded email/password, dashboard redirect and local Google popup.'); return; }
    stage = 'editor';
    const context = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1440, height: 1000 } });
    const page = await context.newPage(); activePage = page;
    await staff(page);
    assert.equal(await page.locator('#event-workspace').isVisible(), false);
    await surface(page, 'admin-list-desktop');
    await page.locator('#event-new').click(); await page.locator('#event-editor-form').waitFor();
    const eventId = await page.locator('#staff-event').inputValue(), slug = `browser-${randomUUID()}`;
    const scheduleYear = new Date().getUTCFullYear() + 1;
    for (const [field, value] of [['startAt', `${scheduleYear}-09-17T09:00`], ['endAt', `${scheduleYear}-09-19T16:56`], ['admissionStartsAt', `${scheduleYear}-09-17T07:56`]]) {
      await page.locator(`[data-field="${field}"]`).fill(value); await page.locator(`[data-field="${field}"]`).dispatchEvent('change');
    }
    await page.locator('[data-field=title]').fill('A Night in Orbit');
    await page.locator('[data-field=title]').dispatchEvent('change');
    await page.locator('[data-field=slug]').fill(slug); await page.locator('[data-field=slug]').dispatchEvent('change');
    await page.locator('[data-field=address]').fill('789 Secret Browser Venue'); await page.locator('[data-field=address]').dispatchEvent('change');
    await page.locator('[data-upload=hero]').setInputFiles(resolve(__dirname, '../../web/gallery/manafest-2026-pink-stage.webp'));
    await page.locator('[data-field="hero.alt"]').waitFor();
    await page.locator('[data-field="hero.alt"]').fill('A colorful festival stage'); await page.locator('[data-field="hero.alt"]').dispatchEvent('change');
    await page.locator('[data-upload=flyer]').setInputFiles({ name: 'broken-flyer.png', mimeType: 'image/png', buffer: Buffer.from('invalid image') });
    await page.locator('[data-upload-status=flyer]').filter({ hasText: 'could not be opened' }).waitFor();
    const flyer = await backend('sharp')({ create: { width: 2800, height: 4200, channels: 3, background: '#72499c' } }).png().toBuffer();
    await page.locator('[data-upload=flyer]').setInputFiles({ name: 'festival-flyer.png', mimeType: 'image/png', buffer: Buffer.concat([flyer, Buffer.alloc(6 * 1024 * 1024)]) });
    await page.locator('[data-field="flyer.alt"]').waitFor();
    await page.locator('[data-field="flyer.alt"]').fill('A purple festival flyer'); await page.locator('[data-field="flyer.alt"]').dispatchEvent('change');
    await page.locator('[data-add=gallery]').click();
    await page.locator('[data-upload="gallery.0"]').setInputFiles(resolve(__dirname, '../../web/gallery/manafest-2026-friends.webp'));
    await page.locator('[data-field="gallery.0.alt"]').waitFor();
    await page.locator('[data-field="gallery.0.alt"]').fill('Friends at the festival'); await page.locator('[data-field="gallery.0.alt"]').dispatchEvent('change');
    await page.locator('[data-field="theme.preset"]').selectOption('light');
    await page.locator('[data-field="theme.accent"]').fill('#161020'); await page.locator('[data-field="theme.accent"]').dispatchEvent('change');
    await page.getByRole('button', { name: 'Save draft', exact: true }).first().click();
    if (!await page.locator('#event-editor-form').evaluate(f => f.reportValidity())) throw new Error('Editor form validation: ' + await page.locator('#event-editor-form :invalid').evaluateAll(e => e.map(i => `${i.dataset.field}: ${i.validationMessage}`).join('; ')));
    await page.locator('#ticketing-message').filter({ hasText: 'Draft saved' }).waitFor().catch(async () => { throw new Error('Editor save status: ' + await page.locator('#ticketing-message').innerText()); });
    let record = (await db.collection('ticketingEvents').doc(eventId).get()).data();
    assert.ok(record.draft.hero.assetId && record.draft.flyer.assetId && record.draft.gallery[0].assetId);
    assert.equal(record.draft.admissionStartsAt, `${scheduleYear}-09-17T11:56:00.000Z`);
    assert.equal(record.draft.offers[0].validFrom, record.draft.admissionStartsAt, 'default ticket admission follows rescheduled event doors');
    assert.equal(record.draft.offers[0].validUntil, record.draft.endAt, 'default ticket admission end follows the event end');
    assert.equal(record.draft.offers[0].salesEnd, record.draft.endAt, 'default sales end follows the event end');
    const flyerAsset = (await db.collection('ticketingEvents').doc(eventId).collection('media').doc(record.draft.flyer.assetId).get()).data();
    assert.ok(flyerAsset.size < 5 * 1024 * 1024, 'large source flyers fit the backend upload limit');
    const flyerMetadata = await backend('sharp')((await backend('firebase-admin/storage').getStorage().bucket(process.env.TICKETING_STORAGE_BUCKET).file(flyerAsset.path).download())[0]).metadata();
    assert.ok(flyerMetadata.width <= 1800 && flyerMetadata.height <= 1800, 'large source flyers are resized before upload');
    stage = 'ticket type saving';
    assert.equal(await page.locator('#event-editor [data-field^="offers."]').count(), 0, 'ticket settings are outside Event Studio');
    await page.locator('#event-orders').click(); await page.locator('#event-ticket-settings-form').waitFor();
    assert.deepEqual(await page.locator('#event-ticket-settings fieldset > legend').allTextContents(), ['Capacity pools', 'Ticket types & passes', 'Promotions', 'Event tax setup', 'Reminders & waitlist']);
    await page.locator('#event-ticket-settings a[href="#event-capacity"]').click();
    await page.locator('[data-field="pools.0.capacity"]').fill('275'); await page.locator('[data-field="pools.0.capacity"]').dispatchEvent('change');
    await page.locator('[data-add=offers]').click();
    await page.locator('[data-field="offers.1.name"]').fill('Vehicle pass'); await page.locator('[data-field="offers.1.name"]').dispatchEvent('change');
    await page.locator('[data-field="offers.1.kind"]').selectOption('vehicle');
    await page.locator('[data-field="offers.1.unitAmount"]').fill('15.50'); await page.locator('[data-field="offers.1.unitAmount"]').dispatchEvent('change');
    await page.locator('[data-field="offers.1.checkInPoints"]').fill('25'); await page.locator('[data-field="offers.1.checkInPoints"]').dispatchEvent('change');
    await page.locator('[data-save-state]').first().filter({ hasText: 'Unsaved changes' }).waitFor();
    await page.getByRole('button', { name: 'Save ticket types', exact: true }).first().click();
    await page.locator('#ticketing-message').filter({ hasText: 'Ticket types saved' }).waitFor();
    await page.locator('[data-save-state]').first().filter({ hasText: 'Saved · Revision' }).waitFor();
    record = (await db.collection('ticketingEvents').doc(eventId).get()).data();
    const vehicleId = record.draft.offers[1].id;
    assert.equal(record.draft.offers[1].unitAmount, 1550); assert.deepEqual(record.draft.offers[1].requiresOfferIds, []);
    assert.equal(record.draft.offers[1].checkInPoints, 25, 'ticket reward is saved from the dashboard editor');
    assert.equal(record.draft.pools[0].capacity, 275);
    await page.locator('#event-ticket-settings a[href="#event-promotions"]').click(); await page.locator('[data-add=promos]').click();
    await page.locator('#event-promotions > details').first().locator('summary').first().click();
    await page.locator('[data-field="promos.0.code"]').fill('ORBIT'); await page.locator('[data-field="promos.0.code"]').dispatchEvent('change');
    await page.locator('#event-ticket-settings a[href="#event-tax"]').click();
    assert.equal(await page.locator('[data-field="tax.performanceLocationId"]').count(), 0, 'sandbox hides advanced tax settings');
    await page.locator('[data-field="tax.mode"]').selectOption('automatic');
    assert.equal(await page.locator('[data-field="tax.autoConfigure"]').isChecked(), true, 'automatic mode defaults to configuring the venue from its address');
    assert.equal(await page.locator('[data-field="tax.performanceLocationId"]').count(), 0, 'automatic setup needs no Stripe IDs');
    await page.locator('[data-field="tax.mode"]').selectOption('sandbox');
    await page.locator('#event-studio').click(); await page.locator('#event-editor-form').waitFor();
    record = (await db.collection('ticketingEvents').doc(eventId).get()).data();
    assert.equal(record.draft.promos[0].code, 'ORBIT'); assert.equal(record.draft.tax.mode, 'sandbox', 'dashboard changes save when moving to the studio');
    assert.equal(record.draft.descriptionHtml, '<p>Tell your guests what makes this event special.</p>');
    assert.equal(await page.locator('#event-editor [data-field^="pools."]').count(), 0);
    assert.equal(await page.locator('#event-editor [data-field^="promos."]').count(), 0);
    assert.equal(await page.locator('#event-editor [data-field^="tax."]').count(), 0);
    await page.locator('#events-back').click(); await page.locator('#events-index:not([hidden])').waitFor();
    await page.locator(`[data-open-event="${eventId}"]`).click();
    await page.locator('#event-dashboard h2').filter({ hasText: 'Orders & event performance' }).waitFor();
    assert.equal(await page.locator('#event-editor').isVisible(), false);
    await page.locator('#event-tickets > details').nth(1).locator('summary').first().click();
    assert.equal(await page.locator('[data-field="offers.1.unitAmount"]').inputValue(), '15.5');
    await surface(page, 'ticket-settings-desktop');
    await page.setViewportSize({ width: 390, height: 844 }); await surface(page, 'ticket-settings-mobile');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.reload(); await page.locator('#event-ticket-settings-form').waitFor();
    await page.locator('#event-tickets > details').nth(1).locator('summary').first().click();
    assert.equal(await page.locator('[data-field="offers.1.unitAmount"]').inputValue(), '15.5');
    stage = 'editor';
    await page.locator('#event-studio').click(); await page.locator('#event-editor-form').waitFor();
    await surface(page, 'studio-desktop'); await page.setViewportSize({ width: 390, height: 844 }); await surface(page, 'studio-mobile'); await page.setViewportSize({ width: 1440, height: 1000 });
    assert.equal((await page.request.get(`${base}/events/${slug}/media/${record.draft.hero.assetId}`)).status(), 404);
    await page.getByRole('button', { name: 'Preview', exact: true }).click();
    await page.locator('#ticketing-dialog iframe').waitFor();
    const preview = page.frameLocator('#ticketing-dialog iframe');
    assert.equal(await preview.locator('h1').innerText(), 'A Night in Orbit');
    assert.ok((await preview.locator('.native-hero-art').getAttribute('src')).startsWith('data:image/webp'));
    assert.ok(!(await preview.locator('body').innerText()).includes('789 Secret Browser Venue'));
    assert.ok(!(await page.locator('#ticketing-dialog iframe').getAttribute('sandbox')).includes('allow-scripts'));
    await page.locator('#ticketing-dialog-close').click();
    await page.getByRole('button', { name: 'Publish', exact: true }).click();
    await page.locator('#ticketing-message').filter({ hasText: 'Event published' }).waitFor();
    const stickyPublish = page.locator('.studio-save-bar [data-studio-publish]');
    assert.equal(await stickyPublish.innerText(), 'Published'); assert.ok(await stickyPublish.isDisabled());
    await page.locator('[data-field=subtitle]').fill('An updated introduction published from the save bar');
    assert.equal(await stickyPublish.innerText(), 'Publish changes', 'editing immediately marks the public page out of date');
    await page.locator('[data-field=subtitle]').dispatchEvent('change');
    await page.locator('#ticketing-message-dismiss').click();
    await stickyPublish.click(); await stickyPublish.filter({ hasText: 'Published' }).waitFor();
    const updatedPublication = (await db.collection('ticketingEvents').doc(eventId).get()).data();
    assert.equal(updatedPublication.publishedRevision, updatedPublication.revision);
    assert.equal(updatedPublication.liveDraft.subtitle, 'An updated introduction published from the save bar', 'publishing saves current edits before updating the live page');
    await page.locator('#event-orders').click(); await page.locator('#event-dashboard > h2').waitFor();
    assert.equal(await page.locator('#event-ticket-settings [data-event-action=publish]').count(), 0, 'published ticket settings need no publish button');
    await page.locator('#event-tickets > details').first().locator('summary').first().click();
    await page.locator('[data-field="offers.0.unitAmount"]').fill('89'); await page.locator('[data-field="offers.0.unitAmount"]').dispatchEvent('change');
    await page.getByRole('button', { name: 'Save ticket types', exact: true }).first().click();
    await page.locator('#ticketing-message').filter({ hasText: 'The public page is updated' }).waitFor();
    assert.equal((await db.collection('publishedEvents').doc(eventId).get()).data().offers[0].unitAmount, 8900, 'saving updates public ticket prices immediately');
    await surface(page, 'dashboard-desktop');
    await page.setViewportSize({ width: 390, height: 844 }); await surface(page, 'dashboard-mobile');
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.locator('#event-cash').click(); await page.locator('#ticketing-dialog[open]').waitFor(); await surface(page, 'cash-dialog'); await page.locator('#ticketing-dialog-close').click();
    await page.locator('#event-roles').click(); await page.locator('#ticketing-dialog[open]').waitFor(); await surface(page, 'roles-dialog'); await page.locator('#ticketing-dialog-close').click();
    await page.locator('#event-studio').click(); await page.locator('#event-editor-form').waitFor();
    const standaloneKey = key(), standalone = await api(page, 'staff/cash', { eventId, accessKey: standaloneKey, items: [{ offerId: vehicleId, quantity: 1 }], name: 'Vehicle Guest', email: 'vehicle@preview.invalid', comp: true, reason: 'Standalone pass test', cashReceived: 0 });
    assert.equal((await api(page, 'order', { orderId: standalone.orderId, accessKey: standaloneKey })).tickets[0].name, 'Vehicle pass');
    const publicPage = await context.newPage();
    for (const mobile of [false, true]) {
      await publicPage.setViewportSize(mobile ? { width: 390, height: 844 } : { width: 1440, height: 1000 });
      await publicPage.goto(`${base}/events/${slug}`);
      await settled(publicPage);
      assert.ok(!(await publicPage.content()).includes('789 Secret Browser Venue'));
      assert.ok(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      const result = await new AxeBuilder({ page: publicPage }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
      assert.deepEqual(result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), []);
      await publicPage.screenshot({ path: `tmp/ticketing-event-${mobile ? 'mobile' : 'desktop'}.png`, fullPage: true });
      await publicPage.goto(`${base}/events`);
      await settled(publicPage);
      assert.ok(await publicPage.locator('.discover-card').count() > 0);
      assert.ok(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      const listingResult = await new AxeBuilder({ page: publicPage }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
      assert.deepEqual(listingResult.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), []);
      await publicPage.screenshot({ path: `tmp/ticketing-list-${mobile ? 'mobile' : 'desktop'}.png`, fullPage: true });
    }
    await page.getByRole('button', { name: 'Duplicate', exact: true }).click();
    await page.locator('#event-editor h2').filter({ hasText: '(copy)' }).waitFor();
    const duplicateId = await page.locator('#staff-event').inputValue();
    const copy = (await db.collection('ticketingEvents').doc(duplicateId).get()).data();
    assert.equal(copy.status, 'draft'); assert.ok(copy.draft.offers.every(o => !o.active));
    assert.equal((await db.collection('ticketingEvents').doc(duplicateId).collection('pools').get()).docs.reduce((n, d) => n + d.data().sold + d.data().held, 0), 0);
    assert.equal((await api(page, 'staff/preview', { eventId: duplicateId })).html.includes('data:image/webp'), true);
    const accessKey = key();
    const comp = await api(page, 'staff/cash', { eventId, accessKey, items: [{ offerId: 'general', quantity: 1 }], name: 'Browser Guest', email: 'browser@preview.invalid', comp: true, reason: 'Browser acceptance test', cashReceived: 0 });
    const view = await api(page, 'order', { orderId: comp.orderId, accessKey });
    assert.equal(view.total, 0); assert.ok(view.tickets[0].qr);
    await page.evaluate(({ orderId, accessKey }) => localStorage.setItem(`pluto-order-${orderId}`, accessKey), { orderId: comp.orderId, accessKey });
    stage = 'app order'; const app = await context.newPage(); activePage = app; await app.goto(`${base}/app/tickets?order=${comp.orderId}`);
    await semantics(app); await revealText(app, 'A Night in Orbit');
    await revealText(app, 'Status: valid');
    await revealText(app, app.getByRole('button', { name: /Admission QR for General admission/ }));
    assert.equal(await app.getByText(/Download.*ticket|Print ticket/).count(), 0);
    await app.screenshot({ path: 'tmp/ticketing-app-order.png' });
    await api(page, 'transfer', { orderId: comp.orderId, accessKey, ticketId: view.tickets[0].id, email: 'recipient@preview.invalid' });
    const transfer = (await db.collection('ticketingEmailJobs').where('orderId', '==', comp.orderId).get()).docs.find(d => d.data().type === 'transfer').data();
    stage = 'app transfer'; await app.goto(`${base}/app/tickets#transfer=${transfer.token}`); await semantics(app);
    await app.getByRole('button', { name: 'Accept ticket' }).click();
    await revealText(app, 'recipient@preview.invalid');
    const after = await api(page, 'order', { orderId: comp.orderId, accessKey }); assert.equal(after.tickets[0].qr, null);
    stage = 'app holder reload'; await app.reload(); await semantics(app); await revealText(app, 'Status: valid');
    stage = 'guest wallet';
    const guestContext = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 320, height: 700 } });
    const guestApp = await guestContext.newPage(); activePage = guestApp;
    await guestApp.goto(base);
    await guestApp.evaluate(token => localStorage.setItem(`pluto-holder-${token}`, token), transfer.token);
    await guestApp.goto(`${base}/app/tickets`); await semantics(guestApp);
    await revealText(guestApp, 'recipient@preview.invalid');
    await guestApp.reload(); await semantics(guestApp); await revealText(guestApp, 'Status: valid');
    await guestApp.screenshot({ path: 'tmp/ticketing-guest-wallet-mobile.png' });
    await guestContext.close();
    stage = 'guest account completion';
    const accountContext = await browser.newContext({ ignoreHTTPSErrors: true, viewport: { width: 1280, height: 900 } });
    const account = await accountContext.newPage(); activePage = account;
    const accountEmail = `account-${randomUUID()}@preview.invalid`, accountKey = key();
    const accountOrder = await api(page, 'staff/cash', { eventId, accessKey: accountKey, items: [{ offerId: 'general', quantity: 1 }], name: 'Account Guest', email: accountEmail, comp: true, reason: 'Account completion test', cashReceived: 0 });
    await account.goto(base);
    await account.evaluate(({ orderId, accessKey }) => localStorage.setItem(`pluto-order-${orderId}`, accessKey), { orderId: accountOrder.orderId, accessKey: accountKey });
    await account.goto(`${base}/app/tickets?order=${accountOrder.orderId}`); await semantics(account);
    await account.getByRole('button', { name: 'Create my account', exact: true }).waitFor();
    await account.getByRole('button', { name: 'Open Pluto app', exact: true }).waitFor();
    await account.screenshot({ path: 'tmp/ticketing-guest-order.png' });
    await account.getByRole('button', { name: 'Create my account', exact: true }).click();
    await account.getByRole('textbox', { name: 'Name', exact: true }).waitFor();
    await account.getByRole('textbox', { name: /Email/ }).focus();
    await account.waitForFunction(expected => [...document.querySelectorAll('input')].some(input => input.value === expected), accountEmail);
    assert.equal(await account.getByRole('textbox', { name: /Email/ }).inputValue(), accountEmail);
    await account.getByRole('textbox', { name: 'Name', exact: true }).focus();
    await account.waitForFunction(expected => [...document.querySelectorAll('input')].some(input => input.value === expected), 'Account Guest');
    assert.equal(await account.getByRole('textbox', { name: 'Name', exact: true }).inputValue(), 'Account Guest');
    await fillFlutterInput(account, 'Password', 'Preview-account-2026!');
    await fillFlutterInput(account, 'Confirm password', 'Preview-account-2026!');
    await account.getByRole('button', { name: 'Create Account', exact: true }).click();
    await account.waitForURL(`${base}/app/tickets?order=${accountOrder.orderId}`);
    await account.getByRole('button', { name: 'Send verification email', exact: true }).waitFor({ timeout: 30000 });
    assert.ok(account.url().includes(`/app/tickets?order=${accountOrder.orderId}`));
    assert.equal((await db.collection('ticketingOrders').doc(accountOrder.orderId).get()).data().ownerUid, '');
    const signupCodes = await (await account.request.get('http://127.0.0.1:9095/emulator/v1/projects/demo-pluto-ticketing/oobCodes')).json();
    assert.equal(signupCodes.oobCodes.filter(c => c.email === accountEmail && c.requestType === 'VERIFY_EMAIL').length, 1, 'ticket-wallet signup sends verification automatically');
    await account.getByRole('button', { name: 'Send verification email', exact: true }).click();
    await account.getByText('Verification email sent. Open the link, then select “I’ve verified my email” here.', { exact: true }).last().waitFor();
    const oob = await (await account.request.get('http://127.0.0.1:9095/emulator/v1/projects/demo-pluto-ticketing/oobCodes')).json();
    assert.ok(oob.oobCodes.some(c => c.email === accountEmail && c.requestType === 'VERIFY_EMAIL'));
    const auth = backend('firebase-admin/auth').getAuth(), accountUser = await auth.getUserByEmail(accountEmail);
    await auth.updateUser(accountUser.uid, { emailVerified: true });
    await account.getByRole('button', { name: 'I’ve verified my email', exact: true }).click();
    await account.getByText(/Your purchases are linked/).waitFor();
    assert.equal((await db.collection('ticketingOrders').doc(accountOrder.orderId).get()).data().ownerUid, accountUser.uid);
    await account.evaluate(() => { for (const key of Object.keys(localStorage)) if (key.startsWith('pluto-order-')) localStorage.removeItem(key); });
    await account.goto(`${base}/app/tickets`); await semantics(account); await revealText(account, 'Status: valid');
    await walletTop(account); await account.getByRole('button', { name: 'Open Pluto app', exact: true }).click(); await account.waitForURL(`${base}/app/`);
    await accountContext.close();
    const activeKey = key(), active = await api(page, 'staff/cash', { eventId: 'ticketing-preview-event', accessKey: activeKey, items: [{ offerId: 'weekend', quantity: 1 }], name: 'Door Guest', email: 'door@preview.invalid', comp: true, reason: 'Offline admission test', cashReceived: 0 });
    const admissionTicket = (await api(page, 'order', { orderId: active.orderId, accessKey: activeKey })).tickets[0];
    stage = 'offline admission'; const door = await context.newPage(); activePage = door; await staff(door, '/tickets/staff'); await door.locator('#staff-event').selectOption('ticketing-preview-event');
    await surface(door, 'admission-desktop');
    await door.setViewportSize({ width: 390, height: 844 }); await surface(door, 'admission-mobile');
    await door.setViewportSize({ width: 1440, height: 1000 });
    await door.locator('#admission-sync').click(); await door.locator('#ticketing-message').filter({ hasText: 'prepared for offline use' }).waitFor();
    await door.evaluate(async () => { await navigator.serviceWorker.ready; }); await door.reload();
    await door.locator('#staff-event').selectOption('ticketing-preview-event'); await door.locator('#admission-cache-status').filter({ hasText: 'Manifest age' }).waitFor();
    await context.setOffline(true); await door.reload(); await door.locator('#staff-controls:not([hidden])').waitFor();
    assert.equal(await door.locator('#staff-event').inputValue(), 'ticketing-preview-event');
    await door.locator('[name=qr]').fill(admissionTicket.qr); await door.locator('#admission-form button').click();
    await door.locator('#admission-results').filter({ hasText: 'Offline: queued' }).waitFor();
    await door.reload(); await door.locator('#staff-controls:not([hidden])').waitFor();
    await door.locator('#ticketing-message').filter({ hasText: 'Prepared offline admission' }).waitFor();
    await door.locator('[name=qr]').fill(admissionTicket.qr); await door.locator('#admission-form button').click();
    await door.locator('#admission-results').filter({ hasText: 'DUPLICATE' }).waitFor();
    await context.setOffline(false); await staff(door, '/tickets/staff');
    await door.locator('#admission-replay').click(); await door.locator('#ticketing-message').filter({ hasText: 'Synced 1 admissions' }).waitFor();
    assert.ok((await db.collection('ticketingTickets').doc(admissionTicket.id).get()).data().admission.offline);
    const conflictKey = key(), conflictOrder = await api(page, 'staff/cash', { eventId: 'ticketing-preview-event', accessKey: conflictKey, items: [{ offerId: 'weekend', quantity: 1 }], name: 'Conflict Guest', email: 'conflict@preview.invalid', comp: true, reason: 'Revoked offline credential test', cashReceived: 0 });
    const conflictTicket = (await api(page, 'order', { orderId: conflictOrder.orderId, accessKey: conflictKey })).tickets[0];
    await door.locator('#admission-sync').click(); await door.locator('#ticketing-message').filter({ hasText: 'prepared for offline use' }).waitFor();
    await api(page, 'staff/refund', { orderId: conflictOrder.orderId, ticketIds: [conflictTicket.id], attempt: key() });
    await context.setOffline(true); await door.locator('[name=qr]').fill(conflictTicket.qr); await door.locator('#admission-form button').click();
    await door.locator('#admission-results').filter({ hasText: 'Offline: queued' }).waitFor();
    await context.setOffline(false); await door.locator('#admission-replay').click();
    await door.locator('#admission-conflicts').filter({ hasText: 'Needs review' }).waitFor();
    const conflictScanId = await door.locator('[data-review-conflict]').getAttribute('data-review-conflict');
    await door.locator('[data-conflict-note]').fill('Verified refunded credential; no additional admission authorized.');
    await door.getByRole('button', { name: 'Reject recorded admission', exact: true }).click();
    await door.locator('#ticketing-message').filter({ hasText: 'resolved with an audit record' }).waitFor();
    assert.equal(await door.locator(`[data-review-conflict="${conflictScanId}"]`).count(), 0);
    const resolvedScan = (await db.collection('ticketingEvents').doc('ticketing-preview-event').collection('scans').doc(conflictScanId).get()).data();
    assert.equal(resolvedScan.resolution.decision, 'reject');
    assert.equal((await db.collection('ticketingTickets').doc(conflictTicket.id).get()).data().status, 'refunded');
    await context.close();
    console.log('Browser checks passed: large flyer and error retry, hero/gallery, private preview, publishing, duplication, explicit ticket saves/reload, standalone vehicle pass, dashboard/studio navigation, desktop/mobile accessibility, app QR/transfer/guest wallet, account signup/verification/claim/reload, offline admission/replay/conflict review.');
  } catch (error) { console.error('Browser phase:', stage); if (activePage) { await activePage.screenshot({ path: 'tmp/ticketing-browser-failure.png' }).catch(() => {}); console.error((await activePage.locator('body').innerText()).slice(0,1500)); } throw error; }
  finally { await browser.close(); }
})().then(() => process.exit(0), error => { console.error(error.message); process.exit(1); });
