name: PR Checks
on:
  pull_request:
    branches: [main]
  push:
    branches: [main, native-ticketing]
  merge_group:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validation:
    uses: ./.github/workflows/validate.yml
